// default package
// Generated 27 feb 2024 12:34:42 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable {

	private Integer cuCodCuenta;
	private Sucursales sucursales;
	private Date cuFechaCreacion;
	private Integer cuSaldo;
	private Set clientes = new HashSet(0);
	private Set transaccioneses = new HashSet(0);

	public Cuenta() {
	}

	public Cuenta(Sucursales sucursales, Date cuFechaCreacion, Integer cuSaldo, Set clientes, Set transaccioneses) {
		this.sucursales = sucursales;
		this.cuFechaCreacion = cuFechaCreacion;
		this.cuSaldo = cuSaldo;
		this.clientes = clientes;
		this.transaccioneses = transaccioneses;
	}

	public Integer getCuCodCuenta() {
		return this.cuCodCuenta;
	}

	public void setCuCodCuenta(Integer cuCodCuenta) {
		this.cuCodCuenta = cuCodCuenta;
	}

	public Sucursales getSucursales() {
		return this.sucursales;
	}

	public void setSucursales(Sucursales sucursales) {
		this.sucursales = sucursales;
	}

	public Date getCuFechaCreacion() {
		return this.cuFechaCreacion;
	}

	public void setCuFechaCreacion(Date cuFechaCreacion) {
		this.cuFechaCreacion = cuFechaCreacion;
	}

	public Integer getCuSaldo() {
		return this.cuSaldo;
	}

	public void setCuSaldo(Integer cuSaldo) {
		this.cuSaldo = cuSaldo;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

	public Set getTransaccioneses() {
		return this.transaccioneses;
	}

	public void setTransaccioneses(Set transaccioneses) {
		this.transaccioneses = transaccioneses;
	}

}
