// default package
// Generated 27 feb 2024 12:34:42 by Hibernate Tools 6.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Sucursales generated by hbm2java
 */
public class Sucursales implements java.io.Serializable {

	private int suCodSucursal;
	private String suCiudad;
	private BigDecimal suActivo;
	private Set cuentas = new HashSet(0);

	public Sucursales() {
	}

	public Sucursales(int suCodSucursal, String suCiudad, BigDecimal suActivo, Set cuentas) {
		this.suCodSucursal = suCodSucursal;
		this.suCiudad = suCiudad;
		this.suActivo = suActivo;
		this.cuentas = cuentas;
	}

	public int getSuCodSucursal() {
		return this.suCodSucursal;
	}

	public void setSuCodSucursal(int suCodSucursal) {
		this.suCodSucursal = suCodSucursal;
	}

	public String getSuCiudad() {
		return this.suCiudad;
	}

	public void setSuCiudad(String suCiudad) {
		this.suCiudad = suCiudad;
	}

	public BigDecimal getSuActivo() {
		return this.suActivo;
	}

	public void setSuActivo(BigDecimal suActivo) {
		this.suActivo = suActivo;
	}

	public Set getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set cuentas) {
		this.cuentas = cuentas;
	}

}
