// default package
// Generated 7 feb 2024 9:41:44 by Hibernate Tools 6.3.1.Final
package modeloVO;

import java.sql.Date;

/**
 * Transacciones generated by hbm2java
 */
public class Transacciones implements java.io.Serializable {

	private Integer id;
	private Cuenta cuenta;
	private Date trFechaTransaccion;
	private Character trTipo;
	private Integer trCantidad;

	public Transacciones() {
	}

	public Transacciones(Cuenta cuenta, Date trFechaTransaccion, Character trTipo, Integer trCantidad) {
		this.cuenta = cuenta;
		this.trFechaTransaccion = trFechaTransaccion;
		this.trTipo = trTipo;
		this.trCantidad = trCantidad;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	public Date getTrFechaTransaccion() {
		return this.trFechaTransaccion;
	}

	public void setTrFechaTransaccion(Date trFechaTransaccion) {
		this.trFechaTransaccion = trFechaTransaccion;
	}

	public Character getTrTipo() {
		return this.trTipo;
	}

	public void setTrTipo(Character trTipo) {
		this.trTipo = trTipo;
	}

	public Integer getTrCantidad() {
		return this.trCantidad;
	}

	public void setTrCantidad(Integer trCantidad) {
		this.trCantidad = trCantidad;
	}

}
